
CREATE TABLE USER_A(
	ID VARCHAR2(200) PRIMARY KEY,
	PASSWORD VARCHAR2(200) NOT NULL,
	NAME VARCHAR2(200) NOT NULL,
	ADDRESS VARCHAR2(200) NOT NULL,
	BIRTHDAY DATE NOT NULL,
	REGISTERDATE DATE NOT NULL
)

DROP TABLE USER_A


INSERT INTO USER_A(ID,PASSWORD,NAME,ADDRESS,BIRTHDAY,REGISTERDATE) VALUES('JAVA','1234','홍길동','경기도 용인',TO_DATE('19980619','YYYYMMDD'),SYSDATE)
INSERT INTO USER_A(ID,PASSWORD,NAME,ADDRESS,BIRTHDAY,REGISTERDATE) VALUES('JAVA3','1234','홍길동','경기도 용인',TO_DATE('1998-06-19','YYYY-MM-DD'),SYSDATE)

SELECT * FROM USER_A

SELECT ID,PASSWORD,NAME,ADDRESS,TO_CHAR(BIRTHDAY,'YYYYMMDD'),TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE),TO_CHAR(BIRTHDAY,'YYYYMMDD')) /12),TO_CHAR(REGISTERDATE,'YYYYMMDD') FROM USER_A

SELECT TO_CHAR(BIRTHDAY,'YYYYMMDD') FROM USER_A