CREATE TABLE WEB_MEMBER(
 ID VARCHAR2(100) PRIMARY KEY,
 PASSWORD VARCHAR2(100) NOT NULL,
 NAME VARCHAR2(100) NOT NULL,
 ADDRESS VARCHAR2(100) NOT NULL
);

INSERT INTO WEB_MEMBER(ID,PASSWORD,NAME,ADDRESS)
VALUES('java','1234','홍길동','판교');

INSERT INTO WEB_MEMBER(ID,PASSWORD,NAME,ADDRESS)
VALUES('servlet','abcd','드레이븐','용인');

SELECT COUNT(*) FROM WEB_MEMBER
SELECT ID,NAME,ADDRESS FROM WEB_MEMBER

//NO, PRODUCT,TOTAL_PRICE,SALES_COUNT FROM 

CREATE TABLE QWE(
	NO NUMBER PRIMARY KEY,
	PRODUCT VARCHAR2(100) NOT NULL,
	PRICE NUMBER NOT NULL,
	TOTAL_PRICE NUMBER,
	SALES NUMBER
)

SELECT * FROM WEB_MEMBER

CREATE SEQUENCE QWE_SEQ;

INSERT INTO QWE(NO,PRODUCT,PRICE,TOTAL_PRICE,SALES) VALUES(QWE_SEQ.NEXTVAL,'삼겹살',9000,0,0)

SELECT NO, PRODUCT, TOTAL_PRICE,SALES FROM QWE