/*
 *  mvc-product.sql
 *  DATE형을 다루어 웹어플리케이션을 구현해보는 예제
 * 
 */ 

CREATE TABLE MVC_PRODUCT(
	ID NUMBER PRIMARY KEY, --고유번호
	NAME VARCHAR2(100) NOT NULL, --이름
	MAKER VARCHAR2(100) NOT NULL, --제조사
	PRICE NUMBER NOT NULL, --가격
	REGDATE DATE NULL --상품등록일
);

CREATE SEQUENCE MVC_PRODUCT_SEQ;

SELECT REGDATE FROM MVC_PRODUCT

SELECT ID,NAME,TO_CHAR(REGDATE,'YYYY-MM-DD') FROM MVC_PRODUCT ORDER BY ID DESC
