CREATE TABLE WEB_PRODUCT(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(100) NOT NULL,
	MAKER VARCHAR2(100) NOT NULL,
	PRICE NUMBER NOT NULL
);

CREATE SEQUENCE WEB_PRODUCT_SEQ

INSERT INTO WEB_PRODUCT VALUES(WEB_PRODUCT_SEQ.NEXTVAL,'카스','두산',1500);
INSERT INTO WEB_PRODUCT VALUES(WEB_PRODUCT_SEQ.NEXTVAL,'테라','진로',1700);
INSERT INTO WEB_PRODUCT VALUES(WEB_PRODUCT_SEQ.NEXTVAL,'참이슬','진로',1300);

SELECT * FROM WEB_PRODUCT

